import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar'
import BreadCrumbs from './components/BreadCrumbs'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Abhinav Parbhakar Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body >
      <NavBar />
        {children}
        </body>
    </html>
  )
}
